---
title: "Tenzin Lhamo's Dashboard for DACSS Data Visualization"
bibliography: library.bib
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard) # always
library(ggplot2)
library(scales)
```

## Intro {.sidebar}

Preparing the dashboard based on the instructions given at @magallanes_reyes_data_2022, and aden-buie_flexdashboard_2024.

### References
<div id="refs"></div>

---

### Deliverable 1 Plot <!-- Suburb Locale Distribution Barplot -->

```{r, cache = FALSE, fig.width = 10, fig.height = 6}
#load the saved plot from the RDS file
plot_data = readRDS('newPlot.rds')
newPlot = plot_data$plot
LABELS = plot_data$labels
print(newPlot)
```

### Deliverable 2 Plot <!-- MA State Police Arrest Type-Age Barplot -->

```{r, cache = FALSE, fig.width = 10, fig.height = 6}
plot2 = readRDS('plot2.rds')
print(plot2)
```


### Deliverable 3 Check Plot <!-- Political Contributions in Boston Choropleths -->

```{r, cache = FALSE, fig.width = 10, fig.height = 6}
plot3 = readRDS('plot3.rds')
print(plot3)
```

Row {data-height=400}
-----------------------------------------------------------------------
  
### Deliver 3 Credit Card Plot
```{r, cache = FALSE, fig.width = 10, fig.height = 6}
plot4 = readRDS('plot4.rds')
print(plot4)
```
